<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>ef</string>
		<string>eft</string>
		<string>efm</string>
		<string>efml</string>
	</array>
	<key>name</key>
	<string>EFML</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>^\s*?(?=\&gt;)</string>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>meta.selector.efml</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#efml-tag</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#efml-tag-class</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#efml-tag-ref</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*?(?=#)</string>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>meta.line.attr.efml</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#efml-attr</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#efml-string</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*?(?=%)</string>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>meta.line.prop.efml</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#efml-prop</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#efml-string</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*?(?=@)</string>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>meta.line.event.efml</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#efml-event</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#efml-event-method</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#efml-string</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*?[+-].*?$</string>
			<key>name</key>
			<string>storage.type.eft</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*?(\.|\|)</string>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>text.efml</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#efml-escape</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#efml-mustache</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*?[^&gt;.|#%@+-]</string>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>comment.line.efml</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>efml-attr</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\#</string>
					<key>end</key>
					<string>(?=\=)|$</string>
					<key>name</key>
					<string>entity.other.attribute-name.html</string>
				</dict>
			</array>
		</dict>
		<key>efml-escape</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\&amp;(u.{0,4}|x.{0,2}|.?)</string>
					<key>name</key>
					<string>constant.character.escape.efml</string>
				</dict>
			</array>
		</dict>
		<key>efml-event</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\@</string>
					<key>end</key>
					<string>((?=\=)|$)</string>
					<key>name</key>
					<string>variable.function.efml</string>
				</dict>
			</array>
		</dict>
		<key>efml-event-method</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?&lt;=\=)</string>
					<key>end</key>
					<string>((?=:)|$)</string>
					<key>name</key>
					<string>entity.name.function.efml</string>
				</dict>
			</array>
		</dict>
		<key>efml-mustache</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\{\{</string>
					<key>end</key>
					<string>\}\}|$</string>
					<key>name</key>
					<string>expression.embbeded.efml</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#mustache-path</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#mustache-string</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>efml-prop</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\%</string>
					<key>end</key>
					<string>((?=\=)|$)</string>
					<key>name</key>
					<string>keyword.control.efml</string>
				</dict>
			</array>
		</dict>
		<key>efml-string</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?&lt;=(\=|:))</string>
					<key>end</key>
					<string>$</string>
					<key>name</key>
					<string>string.efml</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#efml-mustache</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>efml-tag</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\&gt;</string>
					<key>end</key>
					<string>(?=(\.|\#))|$</string>
					<key>name</key>
					<string>entity.name.tag.block.any.efml</string>
				</dict>
			</array>
		</dict>
		<key>efml-tag-class</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\.</string>
					<key>end</key>
					<string>(?=((#([^\}]|\}[^\}])*$)|$))</string>
					<key>name</key>
					<string>meta.selector.css entity.other.attribute-name.class.efml</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#efml-mustache</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>efml-tag-ref</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\#([^\}]|\}[^\}])*$</string>
					<key>end</key>
					<string>$</string>
					<key>name</key>
					<string>entity.other.attribute-name.id.html</string>
				</dict>
			</array>
		</dict>
		<key>mustache-escape</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\&amp;(u(?!}})..(?!}}).(?!}}).|x(?!}}).(?!}}).|(?!}}).)</string>
					<key>name</key>
					<string>constant.character.escape.efml</string>
				</dict>
			</array>
		</dict>
		<key>mustache-path</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?&lt;=\{\{)</string>
					<key>end</key>
					<string>(?=(\=|\}\}|$))</string>
					<key>name</key>
					<string>variable.other.object.efml</string>
				</dict>
			</array>
		</dict>
		<key>mustache-string</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?&lt;=\=)</string>
					<key>end</key>
					<string>(?=\}\})</string>
					<key>name</key>
					<string>string.mustache.efml</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#mustache-escape</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.efml</string>
	<key>uuid</key>
	<string>ee7d9ea0-f056-4365-bc31-0512369e8c17</string>
</dict>
</plist>
